apiVersion: v1
kind: PersistentVolume
metadata:
    name: kafka-pv-01
spec:
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: kafka
    nfs:
        path: /data/kafka/kafka1
        server: 192.168.2.187
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: kafka-pv-02
spec:
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: kafka
    nfs:
        path: /data/kafka/kafka2
        server: 192.168.2.187
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: kafka-pv-03
spec:
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: kafka
    nfs:
        path: /data/kafka/kafka3
        server: 192.168.2.187
