apiVersion: v1
kind: Service
metadata:
  name: hbase-master-a
spec:
  clusterIP: None
  selector:
    app: hbase-master-a
  ports:
    - name: p1
      port: 16000
    - name: p2
      port: 16010
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-master-b
spec:
  clusterIP: None
  selector:
    app: hbase-master-b
  ports:
    - name: p1
      port: 16000
    - name: p2
      port: 16010
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hbase-master-a
  name: hbase-master-a
spec:
  hostAliases:
  - ip: "192.168.2.187"
    hostnames:
    - "k8s-master1"
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HBASE_SERVER_TYPE
      value: master
    - name: HDFS_PATH
      value: mycluster
    - name: ZOOKEEPER_SERVICE_LIST
      value: zk-0.zk-headless.default.svc.cluster.local,zk-1.zk-headless.default.svc.cluster.local,zk-2.zk-headless.default.svc.cluster.local
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: ZNODE_PARENT
      value: hbase
    image: 192.168.1.126/huawei/hbase:v2
    imagePullPolicy: Always
    name: hbase-master-a
    ports:
    - containerPort: 16000
      protocol: TCP
    - containerPort: 16010
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hbase-master-b
  name: hbase-master-b
spec:
  hostAliases:
  - ip: "192.168.2.187"
    hostnames:
    - "k8s-master1"
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HBASE_SERVER_TYPE
      value: master
    - name: HDFS_PATH
      value: mycluster
    - name: ZOOKEEPER_SERVICE_LIST
      value: zk-0.zk-headless.default.svc.cluster.local,zk-1.zk-headless.default.svc.cluster.local,zk-2.zk-headless.default.svc.cluster.local
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: ZNODE_PARENT
      value: hbase
    image: 192.168.1.126/huawei/hbase:v2
    imagePullPolicy: Always
    name: hbase-master-b
    ports:
    - containerPort: 16000
      protocol: TCP
    - containerPort: 16010
      protocol: TCP
