apiVersion: v1
kind: Service
metadata:
  name: p-logstash
  labels: 
    name: p-logstash
spec:
  type: NodePort
  ports:
  - port: 5055
    protocol: TCP
    targetPort: 5055
    name: http
    nodePort: 33550
  selector:
    name: p-logstash
