apiVersion: v1
data:
  filebeat.yml: |
    filebeat.prospectors:
    - input_type: log
      paths:
        - /var/log/nginx/access.log
      fields:
       softname: log
       platform: docker-k8s
      fields_under_root: true
      json.keys_under_root: true
      json.overwrite_keys: true

    output.logstash:
      hosts: ["p-logstash:5055"]
kind: ConfigMap
metadata:
  name: filebeat-conf
  namespace: default
