apiVersion: v1
kind: ReplicationController
metadata:
  name: p-logstash
spec:
  replicas: 1
  selector:
    name: p-logstash
  template:
    metadata:
      labels:
        name: p-logstash
    spec:
      containers:
        - name: p-logstash
          image: 192.168.1.126/huawei/logstash:5.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5055
          volumeMounts:
          - name: config-volume
            mountPath: /etc/logstash/
      volumes:
        - name: config-volume
          configMap:
            name: logstash-conf
