apiVersion: v1
kind: ReplicationController
metadata:
  name: p-logstash-hadoop
spec:
  replicas: 1
  selector:
    name: p-logstash-hadoop
  template:
    metadata:
      labels:
        name: p-logstash-hadoop
    spec:
      hostAliases:
      - ip: "192.168.2.187"
        hostnames:
        - "k8s-master1"
      containers:
        - name: p-logstash-hadoop
          image: 192.168.1.126/huawei/logstash:5.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5055
          volumeMounts:
          - name: config-volume
            mountPath: /etc/logstash/
      volumes:
        - name: config-volume
          configMap:
            name: logstash-conf-hadoop
