apiVersion: v1
kind: Service
metadata:
  name: p-logstash-hadoop
  labels: 
    name: p-logstash-hadoop
spec:
  type: NodePort
  ports:
  - port: 5055
    protocol: TCP
    targetPort: 5055
    name: http
  selector:
    name: p-logstash-hadoop
